import type { CaseCategory } from "@/types/case";

export const categoryLabels: Record<CaseCategory, string> = {
  civil: "민사",
  criminal: "형사",
  divorce: "이혼·가사",
  inheritance: "상속",
};

export const tagLabels: Record<string, string> = {
  civil: "민사",
  debt: "대여금",
  loan: "차용",
  contract: "계약분쟁",
  damages: "손해배상",
  "real-estate": "부동산",
  lease: "임대차",
  eviction: "명도",
  "construction-payment": "공사대금",
  sale: "매매",
  payment: "대금",
  enforcement: "강제집행",
  evidence: "증거",
  "written-confirmation": "각서·확인서",
  criminal: "형사",
  "police-investigation": "경찰조사",
  fraud: "사기",
  embezzlement: "횡령",
  "breach-of-trust": "배임",
  assault: "폭행·상해",
  "sexual-offense": "성범죄",
  dui: "음주운전",
  "voice-phishing": "보이스피싱",
  detention: "구속·영장",
  sentencing: "양형",
  mitigation: "감형",
  divorce: "이혼",
  family: "가사",
  "property-division": "재산분할",
  alimony: "위자료",
  custody: "친권·양육권",
  "child-support": "양육비",
  visitation: "면접교섭",
  "de-facto-marriage": "사실혼",
  affair: "상간자",
  pension: "연금분할",
  "military-pension": "군인연금",
  inheritance: "상속",
  "estate-division": "상속재산분할",
  "reserved-share": "유류분",
  renunciation: "상속포기",
  "limited-acceptance": "한정승인",
  contribution: "기여분",
  "special-benefit": "특별수익",
  will: "유언",
  "inheritance-debt": "상속채무",
};

export const tagsByCategory: Record<CaseCategory | "all", string[]> = {
  all: ["debt", "contract", "property-division", "military-pension", "police-investigation", "reserved-share", "limited-acceptance", "mitigation"],
  civil: ["debt", "loan", "contract", "damages", "real-estate", "lease", "eviction", "sale", "payment", "evidence"],
  criminal: ["police-investigation", "fraud", "embezzlement", "assault", "dui", "detention", "sentencing", "mitigation"],
  divorce: ["property-division", "alimony", "custody", "visitation", "de-facto-marriage", "affair", "pension", "military-pension"],
  inheritance: ["estate-division", "reserved-share", "renunciation", "limited-acceptance", "special-benefit", "will", "inheritance-debt"],
};
